run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - misspell
    - gocyclo
    - godot
    - goimports
    - revive
    - stylecheck
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/LingByte/lingoroutine
  misspell:
    locale: US
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
